POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username": "mentor",
  "password": "mentor",
  "role": "MENTOR"
}

###
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
