GET http://localhost:8080/users/current
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyOTIzMjYwMywicm9sZXMiOlsiQURNSU4iXX0.ab8VN7Tzc476CJhV_eeqRsO37qgzdcGdppQFQabFKQ8

###
