GET http://localhost:8080/users/current
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtZW50b3IgMSIsImV4cCI6MTYzMjUwMjYxMSwicm9sZXMiOlsiTUVOVE9SIl19.v9sKm0xO8US9LKM59KCHVFKKaQm8TuGKEGlDhOO7dr4

###
