GET http://localhost:8080/admin/course-seasons
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyOTczNTMxMywicm9sZXMiOlsiQURNSU4iXX0.-E9mTpI3PtyFpLDrtma8D3m-mk5uh6eEfmreiURyb-Y

###
POST http://localhost:8080/admin/course-seasons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyOTgyMzQ3Nywicm9sZXMiOlsiQURNSU4iXX0.rxT9VKyA_IthEgdDQglLo3Bhdd1col32J0GoqmBAV9w

###

POST http://localhost:8080/admin/seasons/9/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyOTEzNjI3OCwicm9sZXMiOlsiQURNSU4iXX0.YJxl7Th63onEChqZmSoL6eMsTPMBvcXu_93F-VRfsuc

{
  "name": "Node.js",
  "type": "GENERAL"
}

###
GET http://localhost:8080/admin/seasons/9/courses
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyOTIzMjYwMywicm9sZXMiOlsiQURNSU4iXX0.ab8VN7Tzc476CJhV_eeqRsO37qgzdcGdppQFQabFKQ8

###
