###
POST http://localhost:8080/admin/courses/65/mentors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYzMjUwMjU3Miwicm9sZXMiOlsiQURNSU4iXX0.aXC1qgGTlIpB8PAAuN78inYUqeeep6clO_nn23V_GJE

{
  "userId": 71
}
